### PR TITLE
Fix cromwell resource usage when missing log data

### PR DESCRIPTION
**Pull request by TedBrookings**
Sometimes initial CPU usage is missing from the first line of
monitoring log entries. Previously this caused errors because
get_cromwell_resource_usage2.sh analyzed log lines by taking the nth
run of non-whitespace characters to correspond to the nth header column
(resulting in a misalignment if a column was missing). This updates
get_cromwell_resource_usage2.sh to correctly align data by taking
non-whitespace characters from column ranges that correspond to the
header text.

### CODE REVIEW

**Comment by epiercehoffman** [comment]
Not sure why, but it made a lot more things `nan`? This is what the first few lines looked like before the change:
```
ElapsedTime     nCPU    CPU     TotMem  Mem     MemPct  TotDisk Disk    DiskPct IORead  IOWrite task
05:11:08        4       100.0   19.56   17.32   88.6    20.0    8.4     43.0    50.791  122.201 GenotypePESRPart1/TrainSRGenotyping/GenotypeSRPart1
00:03:34        1       100.0   3.60    2.23    62.0    9.9     0.3     3.0     0.074   7.100   GenotypePESRPart2/AddGenotypesBca/shard-0
00:03:25        1       100.0   3.60    1.97    54.8    9.9     0.3     3.0     0.078   6.923   GenotypePESRPart2/AddGenotypesBca/shard-1
00:03:45        1       100.0   3.60    2.32    64.3    9.9     0.4     5.0     0.066   6.951   GenotypePESRPart2/AddGenotypesBca/shard-2
```

And, for the same workflow, this is what the first few lines looked like with the revised script: 

```
ElapsedTime     nCPU    CPU     TotMem  Mem     MemPct  TotDisk Disk    DiskPct IORead  IOWrite task
05:11:08        4       9       5.      19.56   95      2       9.8     7.0     20.0    9       35.     50.791  0       988     nan     GenotypePESRPart1/TrainSRGenotyping/GenotypeSRPart1
00:03:34        1       nan     3.60    nan     62.0    0.      9.9     3       3.0     nan     nan     nan     GenotypePESRPart2/AddGenotypesBca/shard-0
00:03:25        1       nan     3.60    nan     54.8    0.      9.9     3       3.0     nan     nan     nan     GenotypePESRPart2/AddGenotypesBca/shard-1
00:03:45        1       nan     3.60    nan     64.3    0.      9.9     4       5.0     nan     nan     nan     GenotypePESRPart2/AddGenotypesBca/shard-2
```

**Comment by TedBrookings** [comment]
@epiercehoffman That doesn't look good but it's hard to know what's going on from those results. Do you think you could send/link me the log files for those 4 tasks?

**Review by mwalker174 — APPROVED** [review]
Working now, thanks!

**Review by epiercehoffman — APPROVED** [review]
This fixed the issue I was seeing! 

I also tested the -r, -u, -o, workflow ID, and bucket options in the name of thoroughness (although I did not test all combos), and I verified that the -r -u output worked with the analysis script. I didn't really look over the code though because the level of bash is beyond me. 

Looks good, and thanks for hopping on this so quickly!

**Pull request merged**
