### PR TITLE
Include SVTK documentation in README

### PR DESCRIPTION
**Pull request by kjaisingh**
Includes a simple overview and installation details for SVTK.

### CODE REVIEW

**Comment by VJalili** [comment]
Thanks for extending the package description and how to install it. 

I think such details better fit on [this README](https://github.com/broadinstitute/gatk-sv/blob/main/src/svtk/README.md).

**Comment by kjaisingh** [comment]
@VJalili Thanks for the catch, wasn't aware this existed - just updated it, as the previous repository it linked to is now archived.

**Review by epiercehoffman — APPROVED** [review]
Thanks for helping keep our docs up to date!

**Review by VJalili — APPROVED** [review]
Thank you @kjaisingh! LGTM.

**Pull request merged**
