### PR TITLE
Fix issues in definitions of pesr exclude list and sd files in single sample pipeline Terra workspace template files

### PR DESCRIPTION
**Pull request by cwhelan**
A couple of bugs seem to have crept into the Terra workspace template files for the single sample pipeline. In particular, the default setup was failing due to errors in the definitions or specified locations of the PESR exclude list and ref panel SD files. This PR fixes those issues. Relevant to https://github.com/broadinstitute/gatk-sv/issues/412.

### CODE REVIEW

**Review by epiercehoffman — APPROVED** [review]
LGTM

**Review by mwalker174 — APPROVED** [review]
Looks good to me as well.

On a tangential note, this workspace.tsv file format is not formatted well for tracking changes in git and is very hard to read. We should think about generating it from a templated version that's transposed.

**Comment by epiercehoffman** [comment]
> On a tangential note, this workspace.tsv file format is not formatted well for tracking changes in git and is very hard to read. We should think about generating it from a templated version that's transposed.

Agreed and I have also opened a feature request for Terra to use a different format for workspace.tsv https://support.terra.bio/hc/en-us/community/posts/9319574881819-Make-workspace-tsv-format-edit-friendly-git-friendly

**Comment by cwhelan** [comment]
Good idea -- agreed that's it's hard to edit and track changes to that file -- and thanks for opening the feature request. Created a ticket to potentially switch to generating it from a transposed table: https://github.com/broadinstitute/gatk-sv/issues/432

**Pull request merged**
