### PR TITLE
Fix Module0506 inputs for Batch and SingleSample wdls

### PR DESCRIPTION
**Pull request by mwalker174**
Deletes non-existent `disc_files_index` inputs.

### CODE REVIEW

**Comment by henriqueribeiro** [comment]
It seems that something went wrong. Those inputs where added here https://github.com/broadinstitute/gatk-sv/pull/91. However when on this PR https://github.com/broadinstitute/gatk-sv/pull/88 it was erased. I will try to fix it

**Comment by henriqueribeiro** [comment]
I believe it's now fixed https://github.com/broadinstitute/gatk-sv/pull/120

**Comment by mwalker174** [comment]
Looks like something happened off the rebase, probably because the Module0506 WDL got renamed. This issue is now fixed via #120.

**Comment by henriqueribeiro** [comment]
@mwalker174 I believe you have to merge it with master

**Comment by mwalker174** [comment]
Didn't realize that #120 was based on this branch.

**Pull request merged**
