### PR TITLE
Add wrapper workflow to call SubsetVcfBySamplesList task

### PR DESCRIPTION
**Pull request by epiercehoffman**
### Updates
Add wrapper WDL to call SubsetVcfBySamplesList task to be able to run it as a standalone workflow

### Testing
* Validated with womtool
* Tested in Terra on AoU data
* Tested in cromshell on ref panel test data

### CODE REVIEW

**Review by mwalker174 — CHANGES_REQUESTED** [review]
Thanks, can you include a json template for this? Just use the ref panel cleaned vcf and make up a sample subset list and it in `gs://gatk-sv-ref-panel-1kg/test_inputs/`

**Comment by epiercehoffman** [comment]
> Thanks, can you include a json template for this? Just use the ref panel cleaned vcf and make up a sample subset list and it in `gs://gatk-sv-ref-panel-1kg/test_inputs/`

I didn't see that subdirectory so I put it in `gs://gatk-sv-resources-public/hg38/v0/sv-resources/ref-panel/1KG/v1/`, but I can create the `test_inputs` subdirectory and move it if that's preferable

**Comment by mwalker174** [comment]
@epiercehoffman  Yes you can just create the directory. We should keep the test data, which get frequently, in this separate bucket and reserve the resource bucket for permanent files.

**Comment by epiercehoffman** [comment]
Updated to make SubsetVcfBySamplesList task flexible. Toggle remove_samples to either keep or remove the samples in the provided list, and remove_private_sites to set or not set --min-ac 1. 
* Accordingly update WDLs that use the task
* Use this task instead of ExcludeOutliers to remove outlier samples in FilterBatchSamples and FilterOutlierSamples

Testing:
* Validated all WDLs and JSONs with womtool
* Tested SubsetVcfBySamplesList workflow with all 4 combinations of remove_samples and remove_private_sites settings and confirmed that the output VCF had a corresponding number of records and samples

**Review by mwalker174 — APPROVED** [review]
This is great! Good to merge I think.

**Pull request merged**
