### PR TITLE
Deprecate Google Cloud configuration JSONs

### PR DESCRIPTION
**Pull request by kjaisingh**
This PR addresses Issue https://github.com/broadinstitute/gatk-sv/issues/709.

### Description
Deprecates all `google_cloud.*.json` files, as well as the `CLOUD_ENV` variable, as these are no longer used in building inputs for workflows. Also removes any code or documentation references to these.

### Testing
Successfully ran the two commands listed below. The first command does not utilize the `-c` parameter, which was traditionally used to pass in the Google Cloud configuration details.

```
bash scripts/inputs/build_default_inputs.sh -d .
```
```
bash scripts/test/validate.sh -d . -j womtool-87.jar -t
```

### CODE REVIEW

**Comment by kjaisingh** [comment]
@VJalili I believe that the PR already includes changes to relevant documentation files (which are listed below), but please let me know if I am missing anything else here.
- `README.md`
- `website/docs/advanced/build_inputs.md`
- `website/docs/gs/quick_start.md`

**Comment by VJalili** [comment]
You're right; thanks for pointing out the changes.

**Review by epiercehoffman — APPROVED** [review]
Thanks for cleaning this up! I'm excited to not have to deal with this JSON anymore

**Review by kjaisingh — COMMENTED** [review]
Modified as discussed.

**Comment by VJalili** [comment]
@kjaisingh, this is a long-wanted deprecation! Thank you!! :tada: :tada:

**Review by VJalili — APPROVED** [review]

**Pull request merged**
