### PR TITLE
Update python scripts to adhere with PEP8 style guide 

### PR DESCRIPTION
**Pull request by VJalili**
To update python scripts to adhere to PEP8 styling guides, I first used [`autopep8`](https://github.com/hhatto/autopep8) to make the "simple" correction (using the following script), then I [manually corrected the issues not fixed by `autopep8`](https://github.com/broadinstitute/gatk-sv/pull/183/commits/42ec8d2518a449839a1785ce7489f749d8dfbf45) (in the order of a few hundred issues).

```shell
#!/bin/sh

for file in $(find . -name "*.py")
do
    autopep8 -i "$file" --ignore W50
done
```

[`Black`](https://black.readthedocs.io/en/latest/) is an alternative to autopep8, but I found it a bit more "invasive" than autopep8. 

Some changes introduced in this PR may not be the ideal style updates; however, they are the quickest ones to adhere to PEP8 styling guides, which hopefully we can incrementally improve. 

About the made changes:

- `"variable 'XYZ' is assigned to but never used"`; all such cases are commented out, which might be safer for the first pass.
- There has been calls to methods without importing their containing package.  For example, use of `path.splitext(...)`, which changed to `import os` and `os.path.splitext`.
- [There is a list of types of style checks that are skipped,](https://github.com/VJalili/gatk-sv/blob/1d3af923787f97b53260d77ba4110bbab3e04e85/tox.ini#L8) these will need some extra work that we can include on a different PR.
- [There is a list of files excluded from checks.](https://github.com/VJalili/gatk-sv/blob/1d3af923787f97b53260d77ba4110bbab3e04e85/tox.ini#L25-L51) The issues with these files need more careful consideration, hence I'm leaving them for separate PRs.

### CODE REVIEW

**Review by mwalker174 — COMMENTED** [review]
This is great, thank you @VJalili ! I do think we should run a full test, especially since you made changes manually. Can you please rebuild the following dockers: cnmops, melt, sv-pipeline-base, sv-pipeline, sv-pipeline-children-r, sv-pipeline-qc, sv-pipeline-rdtest? Then update `/input_values/dockers.json` and run `scripts/inputs/build_default_inputs.sh`, and finally run single-sample and cohort mode tests using `inputs/GATKSVPipelineSingleSample.ref_panel_1kg.na12878.json` and `test_inputs/large/batch/GATKSVPipelineBatch.json`.

**Comment by VJalili** [comment]
@mwalker174 thank you for the review! We should certainly run a full pipeline test to make sure nothing is broken.

**Comment by VJalili** [comment]
The tests for batch and single pipelines succeeded; here are the comparison of `cleaned_vcf_*_count` fields in metrics files: 

- Single sample: 
  | cleaned_vcf_BND_count | 772.0  | 771.0  |
  |-----------------------|--------|--------|
  | cleaned_vcf_CNV_count | 594.0  | 592.0  |
  | cleaned_vcf_CPX_count | 97.0   | 84.0   |
  | cleaned_vcf_CTX_count | 0.0    | 0.0    |
  | cleaned_vcf_DEL_count | 4839.0 | 4854.0 |
  | cleaned_vcf_DUP_count | 2009.0 | 2002.0 |
  | cleaned_vcf_INS_count | 2702.0 | 2713.0 |
  | cleaned_vcf_INV_count | 9.0    | 9.0    |

- Batch:
  | cleaned_vcf_BND_count  | 5509.0  | 4944.0  |
  |------------------------|---------|---------|
  | cleaned_vcf_CNV_count  | 213.0   |         |
  | cleaned_vcf_CPX_count  | 596.0   | 289.0   |
  | cleaned_vcf_CTX_count  | 0.0     | 0.0     |
  | cleaned_vcf_DEL_count  | 19887.0 | 19828.0 |
  | cleaned_vcf_DUP_count  | 6179.0  | 6403.0  |
  | cleaned_vcf_INS_count  | 11782.0 | 11323.0 |
  | cleaned_vcf_INV_count  | 58.0    | 57.0    |
  | cleaned_vcf_MCNV_count | 290.0   |         |

## Some details

Cromshell commands used to submit the workflows are: 

- Single sample: 
  `cromshell submit wdl/GATKSVPipelineSingleSample.wdl inputs/GATKSVPipelineSingleSample.ref_panel_1kg.na12878.json options.json wdls.zip`

- Batch:
  `cromshell submit wdl/GATKSVPipelineBatch.wdl test_inputs/large/batch/GATKSVPipelineBatch.json options_batch.json wdls.zip`


To reproduce reports, you may run: 

- Single sample: 

```shell
# Get metadata file
$ cromshell -t 90 metadata ee5c4c3f-9de5-447b-819c-b1944ad520ad > metadata_single_sample.json

# Get metrics of the workflow
$ gsutil cp $(cat metadata_single_sample.json | jq -r '.outputs."GATKSVPipelineSingleSample.metrics_file"') single_sample_metrics.tsv

# Get baseline metrics
$ gsutil cp gs://fc-02a6856c-3d17-4379-8e8d-6e0a6fb808cc/1266220c-e33c-4cf4-b58b-e935b9be10bf/GATKSVPipelineSingleSample/5e1c470c-95ff-46da-b664-dae184db0908/call-SingleSampleMetrics/SingleSampleMetrics/3abf17d2-fd5b-4690-a90c-ce52d449bae3/call-CatMetrics/single_sample.NA12878.metrics.tsv single_sample_metrics_baseline.tsv

# Run a comparison
$ svtest plot-metrics single_sample_metrics.tsv single_sample_metrics_baseline.tsv single_sample.pdf --metrics-out single_sample_metrics_comparison.tsv

# Extract only `cleaned_vcf_*_count`
$ grep -i "cleaned_vcf_[a-z]*_count" single_sample_metrics_comparison.tsv
cleaned_vcf_BND_count	772.0	771.0
cleaned_vcf_CNV_count	594.0	592.0
cleaned_vcf_CPX_count	97.0	84.0
cleaned_vcf_CTX_count	0.0	0.0
cleaned_vcf_DEL_count	4839.0	4854.0
cleaned_vcf_DUP_count	2009.0	2002.0
cleaned_vcf_INS_count	2702.0	2713.0
cleaned_vcf_INV_count	9.0	9.0
```

- Batch
```shell
# Get metadata file
$ cromshell -t 90 metadata 004f730b-4ce8-4b48-a57a-d69462a503aa > metadata_batch.json

# Get metrics of the workflow
$ gsutil cp $(cat metadata_batch.json | jq -r '.outputs."GATKSVPipelineBatch.metrics_file"') batch_metrics.tsv

# Get baseline metrics
$ gsutil cp gs://gatk-sv-resources/test/batch/batch_sv.test_large.metrics.tsv batch_metrics_baseline.tsv 

# Run a comparison
$ svtest plot-metrics batch_metrics.tsv batch_metrics_baseline.tsv batch.pdf --metrics-out batch_metrics_comparison.tsv

# Extract only `cleaned_vcf_*_count`
$ grep -i "cleaned_vcf_[a-z]*_count" batch_metrics_comparison.tsv
cleaned_vcf_BND_count	5509.0	4944.0
cleaned_vcf_CNV_count	213.0	
cleaned_vcf_CPX_count	596.0	289.0
cleaned_vcf_CTX_count	0.0	0.0
cleaned_vcf_DEL_count	19887.0	19828.0
cleaned_vcf_DUP_count	6179.0	6403.0
cleaned_vcf_INS_count	11782.0	11323.0
cleaned_vcf_INV_count	58.0	57.0
cleaned_vcf_MCNV_count		290.0
```

**Review by mwalker174 — APPROVED** [review]
LGTM - there are some minor differences in the single-sample results that we should look into, but nothing concerning enough to hold this up.

**Pull request merged**
