### PR TITLE
Add scramble docker input

### PR DESCRIPTION
**Pull request by mwalker174**
Missing from #259 for building inputs.

### CODE REVIEW

**Review by TedBrookings — APPROVED** [review]
Looks good

**Comment by tedsharpe** [comment]
Did you want to make the PESRCollection change at the same time?

**Comment by tedsharpe** [comment]
-    /gatk/gatk --java-options "-Xmx~{command_mem_mb}m" PairedEndAndSplitReadEvidenceCollection \
+    /gatk/gatk --java-options "-Xmx~{command_mem_mb}m" CollectSVEvidence \
         -I ~{cram} \
-        --pe-file ~{sample_id}.disc.txt.gz \
-        --sr-file ~{sample_id}.split.txt.gz \
+        --pe-file ~{sample_id}.pe.txt.gz \
+        --sr-file ~{sample_id}.sr.txt.gz \
         --sample-name ~{sample_id} \
         -R ~{reference_fasta}
 
-    tabix -f -s1 -b 2 -e 2 ~{sample_id}.disc.txt.gz
-    tabix -f -s1 -b 2 -e 2 ~{sample_id}.split.txt.gz
+    tabix -f -s1 -b 2 -e 2 ~{sample_id}.pe.txt.gz
+    tabix -f -s1 -b 2 -e 2 ~{sample_id}.sr.txt.gz

**Comment by mwalker174** [comment]
Good call, I'll just make another PR for that

**Pull request merged**
