### PR TITLE
Maintain a mirror of images on GCR and ACR.

### PR DESCRIPTION
**Pull request by VJalili**
This PR extends the `Docker Images` action to build and push docker images to Google Container Registry (GCR) and Azure Container Registry (ACR), maintaining a mirror of the GATK-SV docker images on both registries. 

This PR also adds two copies of the `dockers.json`, named `dockers_gcp.json` and `dockers_azure.json`. The `dockers_azure.json` is mostly a placeholder and will be updated with the list of docker images on ACR.

### CODE REVIEW

**Comment by mwalker174** [comment]
Do we need this now or could we wait until we can populate the ACR dockers list with actual mirrors?

**Comment by VJalili** [comment]
We could hold this PR until we have built all the images and pushed them to ACR. I can then update `dockers_azure.json` and we can merge this PR then.

**Comment by VJalili** [comment]
@mwalker174 I pushed all the images to ACR.

**Review by mwalker174 — APPROVED** [review]

**Comment by VJalili** [comment]
Thanks @mwalker174.

**Pull request merged**
