### PR TITLE
Remove unused ped_file input from GenotypeBatch and RegenotypeCNVs wdls

### PR DESCRIPTION
**Pull request by kirtanav98**
The ped_file input to GenotypeBatch and RegenotypeCNVs is not used and is removed since the only task it is used in is RdTest, but is not used by the script because none of the plotting functionality is enabled.
The ped_file input to GenotypeBatch.wdl and RegenotypeCNVs.wdl is removed, as well as the SubsetPedFile step in both workflows.
The ped_file, ped_subset_file andr famfile inputs to the subworkflows and tasks called from GenotypeBatch and RegenotypeCNVs are also removed.
The famfile input to the RdTest task in TasksGenotypeBatch and Genotype_2 were made optional in the inputs block and when passed to the script.
The ped_file input to GenotypeBatch and RegenotypeCNVs in GATKSVPipelineBatch and GATKSVPipelineSingleSample were removed.
The ped_file input from the GenotypeBatch and RegenotypeCNVs JSON templates (test and terra) were removed.
The JSONS from the templates were built, and the JSONS and WDLS were validated with in cromshell and on Terra with womtool and the Terra validation script. GenotypeBatch and RegnotypeCNV's was sucessfully run with reference panel data.
This addresses issue [538](https://github.com/broadinstitute/gatk-sv/issues/538).

### CODE REVIEW

**Review by VJalili — COMMENTED** [review]
We have ported the readme to a technical documentation website (you may refer to [this page](https://github.com/broadinstitute/gatk-sv/tree/main/website) for details on the website). Therefore, further updates on the readme are not encouraged as they will lead to a re-synch between the website and the README. Since the changes you are making on the README in this PR are not reflected in the website, you may keep the changes as they are, but for future PR, please target the website. 

Also, please make the PR title more descriptive, and extend the description as @shadizaheri suggested. Descriptive titles and thorough explanations of the motivation help us track the changes and their motivations when reviewing and generating release notes.

**Review by shadizaheri — COMMENTED** [review]
@kirtanav98, Thank you for your efforts in this PR and for addressing the comments! Overall, this PR and the changes made look great to me. I have one question: Was this PR (more specifically GenotypeBatch and RegenotypeCNVs wdls) tested exclusively with Cromwell, or was it also tested on Terra?

**Comment by kirtanav98** [comment]
Thank you for your comment @VJalili, and I addressed your [concerns](https://github.com/broadinstitute/gatk-sv/pull/545#pullrequestreview-1477410735) above. Also thank you @shadizaheri, I addressed your [concerns](https://github.com/broadinstitute/gatk-sv/pull/545#pullrequestreview-1480466054) in the description as well.

**Comment by shadizaheri** [comment]
Thanks @kirtanav98 for your work on this. It looks good to me. Congrats on your first major PR!

**Review by shadizaheri — APPROVED** [review]

**Pull request merged**
