### PR TITLE
Remove old WDL headers with outdated firecloud, license, copyright references

### PR DESCRIPTION
**Pull request by epiercehoffman**
### Updates
Remove outdated WDL headers, including:
* References to firecloud
* Copyright statements - now covered by repository license
* License statements - now covered by repository license

Left intact header lines with author information and workflow descriptions.

### Testing
Validated with womtool using validation script.

### CODE REVIEW

**Review by cwhelan — APPROVED** [review]
Looks good to me. This would address open issue https://github.com/broadinstitute/gatk-sv/issues/7 .

**Review by mwalker174 — APPROVED** [review]
This is marvelous! I would make one suggestion to change the author lines from using `Contact` to `Author` so users won't think they should message individuals with issues.

**Comment by epiercehoffman** [comment]
> Looks good to me. This would address open issue #7 .

Thanks for pointing me to the relevant issue! That issue also says we should add updated headers with descriptions of the workflow, but it seems to me like it would be easier to maintain that documentation in just one place - the README. Thoughts? Do you think I should leave issue #7 open to add new headers or close it?

**Comment by cwhelan** [comment]
> Thanks for pointing me to the relevant issue! That issue also says we should add updated headers with descriptions of the workflow, but it seems to me like it would be easier to maintain that documentation in just one place - the README. Thoughts? Do you think I should leave issue #7 open to add new headers or close it?

Eh, I guess you could just comment on that issue that this ticket partially addressed it by removing the old headers. Adding new headers and documentation to the top level WDLs is a bigger job, but might be nice, especially for people who discover them via Dockstore, for example.

**Pull request merged**
