### PR TITLE
force tabix to overwrite file if it exists

### PR DESCRIPTION
**Pull request by henriqueribeiro**
When running the pipeline in local or shared filesystems, the pipeline sometimes fail because the index files are already there. With that in mind, I'm suggesting to add the `-f` flag to all `tabix` commands. 

Let me know if this make sense or if you would prefer to do it in some other way. 

Thanks

### CODE REVIEW

**Review by mwalker174 — APPROVED** [review]
Thanks @henriqueribeiro, this seems like an easy win for those running locally.

**Comment by henriqueribeiro** [comment]
you are welcome @mwalker174 :rocket:

**Comment by henriqueribeiro** [comment]
@mwalker174 do not merge it yet. This might cause some unexpected behavior with concurrent tasks. I'm analyzing it

**Comment by mwalker174** [comment]
The better solution would be to check for tasks that require inputs to be indexed and call tabix in the tasks where they are generated.

**Comment by mwalker174** [comment]
@henriqueribeiro Any updates on this?

**Comment by spatel-gfb** [comment]
@mwalker174 : This is handled in the PR we raised for [ AWS ](https://github.com/broadinstitute/gatk-sv/pull/309) .

We would need help in suggestions for 2 wdl's in question so we can resolve it and get that in.

**Comment by henriqueribeiro** [comment]
@mwalker174 exactly as @spatel-gfb said. his PR covers these changes too

**Comment by mwalker174** [comment]
@henriqueribeiro Closing since this has been inactive for some time. Please re-open if you would like to submit changes.

**Pull request closed without merging**
