### PR TITLE
Cleanup file headers: remove license and author contact information

### PR DESCRIPTION
**Pull request by VJalili**
This PR improves on file headers by making the following changes:
- removes license headers such as "Copyright (c) * Distributed under *";
- remove author name and contact information.

### CODE REVIEW

**Comment by epiercehoffman** [comment]
Can we retain original author information for scripts that have that information on the copyright line (not a separate contact line) as well?

**Comment by VJalili** [comment]
We could do retain original author information for quicker ref, or alternatively, we could rely on git log. Are you suggesting a change as the following? 

- from
    ```
    # Copyright (c) 2017 X <X@Y>
    # Distributed under terms of the MIT license.
    ```
- to
    ```
    # Original author X
    ```

**Comment by epiercehoffman** [comment]
Yes, either that or remove all author information. I am ok with either as long as there is consistency

**Comment by VJalili** [comment]
My vote is also to remove all the author information from headers.

**Review by mwalker174 — APPROVED** [review]
Thank you @VJalili, this looks good to me. I agree that just removing the author name is the best way forward.

**Comment by VJalili** [comment]
Thank you @epiercehoffman and @mwalker174 for reviewing this.

**Pull request merged**
